// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKfzbXFpsjqIBNXe6ykEG7S9qLE2hosFE',
    appId: '1:104127666463:web:d75b2d67d0efa78777382a',
    messagingSenderId: '104127666463',
    projectId: 'todos-bf4ab',
    authDomain: 'todos-bf4ab.firebaseapp.com',
    storageBucket: 'todos-bf4ab.appspot.com',
    measurementId: 'G-93XVCKSLYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLkdVoVS-QVz6FPrtJyaHcJznQZf-WL34',
    appId: '1:104127666463:android:59eeb21997c2ba3777382a',
    messagingSenderId: '104127666463',
    projectId: 'todos-bf4ab',
    storageBucket: 'todos-bf4ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXlYSZGAJ5DKkgjWdVRq9X2HEdrfL3548',
    appId: '1:104127666463:ios:b194ac4ee8e9cacf77382a',
    messagingSenderId: '104127666463',
    projectId: 'todos-bf4ab',
    storageBucket: 'todos-bf4ab.appspot.com',
    iosClientId: '104127666463-suti224ila9ig014sooi4i8vua2d1k2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXlYSZGAJ5DKkgjWdVRq9X2HEdrfL3548',
    appId: '1:104127666463:ios:b194ac4ee8e9cacf77382a',
    messagingSenderId: '104127666463',
    projectId: 'todos-bf4ab',
    storageBucket: 'todos-bf4ab.appspot.com',
    iosClientId: '104127666463-suti224ila9ig014sooi4i8vua2d1k2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.hw1',
  );
}
